export const data = {
  products: [
    {
      _id: "1",
      name: "Curlogy Skin Care Set",
      category: "cosmetics",
      image: "./images/product-1.jpg",
      price: 89.99,
      brand: "Curlogy",
      rating: 4.5,
      numReview: 13,
      description: "Skin care product for women",
    },
    {
      _id: "2",
      name: "Lumin Skin Care Set",
      category: "cosmetics",
      image: "./images/product-2.jpg",
      price: 149.99,
      brand: "Lumin",
      rating: 4.8,
      numReview: 299,
      description: "Exclusive skin care product for women",
    },
    {
      _id: "3",
      name: "Khaki Bag pack",
      category: "Bags and Baggage",
      image: "./images/product-3.jpg",
      price: 99.9,
      brand: "Baggit",
      rating: 4.2,
      numReview: 8,
      description: "Khaki bag for women",
    },
    {
      _id: "4",
      name: "The Ordinary Skin Care set",
      category: "cosmetics",
      image: "./images/product-4.jpg",
      price: 179.9,
      brand: "The Ordinary",
      rating: 4.9,
      numReview: 301,
      description: "Skin care product for women",
    },
    {
      _id: "5",
      name: "Cello Water Bottle",
      category: "Bottles",
      image: "./images/product-5.jpg",
      price: 35,
      brand: "Cello",
      rating: 4.8,
      numReview: 119,
      description: "Green Thermal Water/Tea/Coffee Bottle, 24Hrs",
    },
    {
      _id: "6",
      name: "Adidas Desinger",
      category: "Sneakers",
      image: "./images/product-6.jpg",
      price: 399.9,
      brand: "Adidas",
      rating: 4.5,
      numReview: 72,
      description: "Men's Footwear",
    },
    {
      _id: "7",
      name: "Sony Over-the-ear headphones ",
      category: "Headphones",
      image: "./images/product-7.jpg",
      price: 150,
      brand: "Sony",
      rating: 3.9,
      numReview: 547,
      description: "Dual-driver Headphones, 32ohm output",
    },
    {
      _id: "8",
      name: "Xbox One Controller",
      category: "Game-Controller",
      image: "./images/product-8.jpg",
      price: 32.9,
      brand: "Microsoft",
      rating: 4.5,
      numReview: 199,
      description: "X-box One controller(White)",
    },
  ],
};